<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Storage\Acme.Storage\Acme.Storage.csproj" />
    <ProjectReference Include="..\Acme.DocumentManagement.Domain\Acme.DocumentManagement.Domain.csproj" />
    <ProjectReference Include="..\Acme.DocumentManagement.Application\Acme.DocumentManagement.Application.csproj" />
    <ProjectReference Include="..\..\Persistence\Acme.Persistence\Acme.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
